### ISSUE TITLE
Name?

### ISSUE THREAD

**Issue by threepointone** [mjackson/babel-plugin-unpkg-rewrite#2]
Maybe Babel-plugin-unpkg-rewrite?

Add suggestions, pick a winner, and I'll rename/publish this.

**Comment by hemanth** [comment]
unpkg-rewrite makes more sense.

**Comment by matthewp** [comment]
👍 to babel-plugin-unpkg-rewrite

**Comment by mjackson** [comment]
Yep, that works for me. We could even transfer it into the github.com/unpkg org if you'd like.

**Comment by threepointone** [comment]
@mjackson I would like that :) feel free to move/rename it

**Comment by mjackson** [comment]
Ah, doesn't look like I have the right permissions. Can you add me as an admin or something?

**Comment by threepointone** [comment]
closing :)
